# This is a basic workflow to help you get started with Actions

name: TraceBug

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:       
    - cron: '0 11 */5 * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update submodule 
        run: |
          git init 
          git submodule init
          git submodule foreach update
          git submodule foreach update --init
          git submodule foreach --recursive git submodule update --init
      - name: Commit
        run: |
          git config --global user.email xtpeeps@gmail.com
          git config --global user.name x7peeps
          git add .
          git branch --set-upstream-to origin/master
          git commit -m "Schdule checkpoint over." -a
      - name: Push changes
        uses: ad-m/github-push-action@master 
        with:
          branch: main
          github_token: ${{ secrets.GIT_TOKEN  }}
 
