# This is a basic workflow to help you get started with Actions

name: TraceBug

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:       
    - cron: '0 11 */5 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update submodule Resources/cve
        run: |
          git config --global init.defaultBranch master
          git init 
          git submodule update
#       - name: update submodule Resources/cve
#         run: |
#           cd Resources/cve @ 0c3422e
#           git pull
#       - name: update submodule Resources/cvelist
#         run: |
#           cd Resources/cvelist
#           git pull
      - name: Commit
        run: |
          git config --global user.email xtpeeps@gmail.com
          git config --global user.name x7peeps
          git add .
          git commit -m "Schdule checkpoint over." -a
      - name: Push changes
        uses: ad-m/github-push-action@master 
        with:
          branch: main
          github_token: ${{ secrets.GIT_TOKEN  }}
 
